// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMT_limBVB4s8-tJIyknYp-e-9E0TpEaE',
    appId: '1:296983234994:web:013321f0eeff9afe98fcab',
    messagingSenderId: '296983234994',
    projectId: 'eco-alert-7935c',
    authDomain: 'eco-alert-7935c.firebaseapp.com',
    storageBucket: 'eco-alert-7935c.firebasestorage.app',
    measurementId: 'G-L0LWLQQ4V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLHyC8miBf7CHgX8XKCGUpuehLkHn0NMI',
    appId: '1:296983234994:android:8f6497ada6365c1f98fcab',
    messagingSenderId: '296983234994',
    projectId: 'eco-alert-7935c',
    storageBucket: 'eco-alert-7935c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3KKt1at-iJDEJX_UovIsVlvBAswuTA2o',
    appId: '1:296983234994:ios:47aadd924e5c385f98fcab',
    messagingSenderId: '296983234994',
    projectId: 'eco-alert-7935c',
    storageBucket: 'eco-alert-7935c.firebasestorage.app',
    iosBundleId: 'com.ecoalert.ecoAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3KKt1at-iJDEJX_UovIsVlvBAswuTA2o',
    appId: '1:296983234994:ios:47aadd924e5c385f98fcab',
    messagingSenderId: '296983234994',
    projectId: 'eco-alert-7935c',
    storageBucket: 'eco-alert-7935c.firebasestorage.app',
    iosBundleId: 'com.ecoalert.ecoAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMT_limBVB4s8-tJIyknYp-e-9E0TpEaE',
    appId: '1:296983234994:web:bee7e1fe50d2dc9a98fcab',
    messagingSenderId: '296983234994',
    projectId: 'eco-alert-7935c',
    authDomain: 'eco-alert-7935c.firebaseapp.com',
    storageBucket: 'eco-alert-7935c.firebasestorage.app',
    measurementId: 'G-ZS7JB75BB7',
  );
}
